name: "Test"

on:
    pull_request:
        branches: [ master, stable-* ]

jobs:
    test:
        runs-on: macos-latest
        steps:
            -   name: Install Docker
                run: |
                    brew install podman
                    podman machine init
                    podman machine start
                    podman run hello-world
