name: "Test"

on:
    pull_request:
        branches: [ master, stable-* ]

jobs:
    test:
        runs-on: macos-latest
        steps:
            -   name: Install podman
                run: |
                    brew install podman
                    podman machine init
                    podman machine start
            -   name: Run Nextcloud server
                run: |
                    podman run -d -p 8080:80 ghcr.io/nextcloud/continuous-integration-shallow-server:latest
